### ISSUE TITLE
ais-search-box failed to complete words & clear input in vue-instantsearch@4.3.0

### ISSUE THREAD

**Issue by 9kmmr** [algolia/vue-instantsearch#1096]
**Bug 🐞**

### What is the current behavior?
ais-search-box can not complete word typed in searchbox & clear input button does not work

### Make a sandbox with the current behavior

Here is the sandbox: https://codesandbox.io/s/eager-lake-5ohhq

### What is the expected behavior?
ais-search-box can complete word normally & clear input button should work

### Does this happen only in specific situations?
When using vue-instantsearch@4.3.0 at any version of vue

### What is the version you are using?
vue-instantsearch@4.3.0

**Comment by Haroenv** [comment]
I'm not sure what causes Vue InstantSearch to install the non-latest version of InstantSearch.js, but in the latest version we just fixed a bug there: https://github.com/algolia/instantsearch.js/pull/4990

Here's a sandbox showing if you force the latest version of InstantSearch.js, the search box behaves naturally: https://codesandbox.io/s/still-wave-hrof5?file=/package.json

I'll update the dependency to require at least that version.

**Comment by Haroenv** [comment]
This should no longer happen with version 4.3.1 of Vue InstantSearch, thanks for the report

**Comment by pablo-guelu** [comment]
Wow, I've been struggling with that for some time (search box not clearing up).
I confirm (at least for me) that version 4.3.1 fixes the issue.

Thanks!!

**Comment by Haroenv** [comment]
@pablo-guelu, don't hesitate opening an issue with reproduction so we can fix these issues!

**Comment by nasimuddin01** [comment]
Using the latest version but it didn't resolve it! Still getting the same issue!
